var _open_g_e_x_structs_8h =
[
    [ "Assimp::OpenGEX::Metric", "struct_assimp_1_1_open_g_e_x_1_1_metric.html", "struct_assimp_1_1_open_g_e_x_1_1_metric" ],
    [ "Assimp::OpenGEX::VertexArray", "struct_assimp_1_1_open_g_e_x_1_1_vertex_array.html", "struct_assimp_1_1_open_g_e_x_1_1_vertex_array" ],
    [ "Assimp::OpenGEX::IndexArray", "struct_assimp_1_1_open_g_e_x_1_1_index_array.html", "struct_assimp_1_1_open_g_e_x_1_1_index_array" ],
    [ "Assimp::OpenGEX::Mesh", "struct_assimp_1_1_open_g_e_x_1_1_mesh.html", "struct_assimp_1_1_open_g_e_x_1_1_mesh" ],
    [ "Assimp::OpenGEX::Node", "struct_assimp_1_1_open_g_e_x_1_1_node.html", "struct_assimp_1_1_open_g_e_x_1_1_node" ],
    [ "Assimp::OpenGEX::GeometryNode", "struct_assimp_1_1_open_g_e_x_1_1_geometry_node.html", "struct_assimp_1_1_open_g_e_x_1_1_geometry_node" ],
    [ "Assimp::OpenGEX::LightNode", "struct_assimp_1_1_open_g_e_x_1_1_light_node.html", "struct_assimp_1_1_open_g_e_x_1_1_light_node" ],
    [ "Assimp::OpenGEX::CameraNode", "struct_assimp_1_1_open_g_e_x_1_1_camera_node.html", "struct_assimp_1_1_open_g_e_x_1_1_camera_node" ],
    [ "Assimp::OpenGEX::GeometryObject", "struct_assimp_1_1_open_g_e_x_1_1_geometry_object.html", "struct_assimp_1_1_open_g_e_x_1_1_geometry_object" ],
    [ "Assimp::OpenGEX::LightObject", "struct_assimp_1_1_open_g_e_x_1_1_light_object.html", "struct_assimp_1_1_open_g_e_x_1_1_light_object" ],
    [ "Assimp::OpenGEX::CameraObject", "struct_assimp_1_1_open_g_e_x_1_1_camera_object.html", "struct_assimp_1_1_open_g_e_x_1_1_camera_object" ],
    [ "Assimp::OpenGEX::Matrix", "struct_assimp_1_1_open_g_e_x_1_1_matrix.html", "struct_assimp_1_1_open_g_e_x_1_1_matrix" ],
    [ "Assimp::OpenGEX::Transform", "struct_assimp_1_1_open_g_e_x_1_1_transform.html", "struct_assimp_1_1_open_g_e_x_1_1_transform" ],
    [ "Assimp::OpenGEX::Translation", "struct_assimp_1_1_open_g_e_x_1_1_translation.html", "struct_assimp_1_1_open_g_e_x_1_1_translation" ],
    [ "Assimp::OpenGEX::Rotation", "struct_assimp_1_1_open_g_e_x_1_1_rotation.html", "struct_assimp_1_1_open_g_e_x_1_1_rotation" ],
    [ "Assimp::OpenGEX::Scale", "struct_assimp_1_1_open_g_e_x_1_1_scale.html", "struct_assimp_1_1_open_g_e_x_1_1_scale" ],
    [ "Assimp::OpenGEX::Name", "struct_assimp_1_1_open_g_e_x_1_1_name.html", "struct_assimp_1_1_open_g_e_x_1_1_name" ],
    [ "Assimp::OpenGEX::ObjectRef", "struct_assimp_1_1_open_g_e_x_1_1_object_ref.html", "struct_assimp_1_1_open_g_e_x_1_1_object_ref" ],
    [ "Assimp::OpenGEX::MaterialRef", "struct_assimp_1_1_open_g_e_x_1_1_material_ref.html", "struct_assimp_1_1_open_g_e_x_1_1_material_ref" ],
    [ "Assimp::OpenGEX::BoneRefArray", "struct_assimp_1_1_open_g_e_x_1_1_bone_ref_array.html", "struct_assimp_1_1_open_g_e_x_1_1_bone_ref_array" ],
    [ "Assimp::OpenGEX::BoneCount", "struct_assimp_1_1_open_g_e_x_1_1_bone_count.html", "struct_assimp_1_1_open_g_e_x_1_1_bone_count" ],
    [ "Assimp::OpenGEX::BoneIndex", "struct_assimp_1_1_open_g_e_x_1_1_bone_index.html", "struct_assimp_1_1_open_g_e_x_1_1_bone_index" ],
    [ "Assimp::OpenGEX::BoneWeight", "struct_assimp_1_1_open_g_e_x_1_1_bone_weight.html", "struct_assimp_1_1_open_g_e_x_1_1_bone_weight" ],
    [ "Assimp::OpenGEX::Skeleton", "struct_assimp_1_1_open_g_e_x_1_1_skeleton.html", "struct_assimp_1_1_open_g_e_x_1_1_skeleton" ],
    [ "Assimp::OpenGEX::Skin", "struct_assimp_1_1_open_g_e_x_1_1_skin.html", "struct_assimp_1_1_open_g_e_x_1_1_skin" ],
    [ "Assimp::OpenGEX::Material", "struct_assimp_1_1_open_g_e_x_1_1_material.html", "struct_assimp_1_1_open_g_e_x_1_1_material" ],
    [ "Assimp::OpenGEX::Attrib", "struct_assimp_1_1_open_g_e_x_1_1_attrib.html", "struct_assimp_1_1_open_g_e_x_1_1_attrib" ],
    [ "Assimp::OpenGEX::Param", "struct_assimp_1_1_open_g_e_x_1_1_param.html", "struct_assimp_1_1_open_g_e_x_1_1_param" ],
    [ "Assimp::OpenGEX::Color", "struct_assimp_1_1_open_g_e_x_1_1_color.html", "struct_assimp_1_1_open_g_e_x_1_1_color" ],
    [ "Assimp::OpenGEX::Texture", "struct_assimp_1_1_open_g_e_x_1_1_texture.html", "struct_assimp_1_1_open_g_e_x_1_1_texture" ],
    [ "Assimp::OpenGEX::Atten", "struct_assimp_1_1_open_g_e_x_1_1_atten.html", "struct_assimp_1_1_open_g_e_x_1_1_atten" ],
    [ "Assimp::OpenGEX::Key", "struct_assimp_1_1_open_g_e_x_1_1_key.html", "struct_assimp_1_1_open_g_e_x_1_1_key" ],
    [ "Assimp::OpenGEX::Curve", "struct_assimp_1_1_open_g_e_x_1_1_curve.html", "struct_assimp_1_1_open_g_e_x_1_1_curve" ],
    [ "Assimp::OpenGEX::Animation", "struct_assimp_1_1_open_g_e_x_1_1_animation.html", "struct_assimp_1_1_open_g_e_x_1_1_animation" ],
    [ "Assimp::OpenGEX::OpenGexDataDescription", "struct_assimp_1_1_open_g_e_x_1_1_open_gex_data_description.html", "struct_assimp_1_1_open_g_e_x_1_1_open_gex_data_description" ]
];