var annotated_dup =
[
    [ "engine", null, [
      [ "ecs", null, [
        [ "ComponentArray", "classengine_1_1ecs_1_1_component_array.html", "classengine_1_1ecs_1_1_component_array" ],
        [ "IComponentArray", "classengine_1_1ecs_1_1_i_component_array.html", null ],
        [ "System", "classengine_1_1ecs_1_1_system.html", "classengine_1_1ecs_1_1_system" ]
      ] ],
      [ "Animation", "structengine_1_1_animation.html", null ],
      [ "AnimationSystem", "classengine_1_1_animation_system.html", null ],
      [ "Animator", "structengine_1_1_animator.html", null ],
      [ "Camera", "classengine_1_1_camera.html", "classengine_1_1_camera" ],
      [ "Collision", "structengine_1_1_collision.html", "structengine_1_1_collision" ],
      [ "CollisionSystem", "classengine_1_1_collision_system.html", "classengine_1_1_collision_system" ],
      [ "Connection", "structengine_1_1_connection.html", "structengine_1_1_connection" ],
      [ "Font", "classengine_1_1_font.html", "classengine_1_1_font" ],
      [ "Image", "classengine_1_1_image.html", "classengine_1_1_image" ],
      [ "Mesh", "classengine_1_1_mesh.html", "classengine_1_1_mesh" ],
      [ "Message", "structengine_1_1_message.html", "structengine_1_1_message" ],
      [ "Model", "classengine_1_1_model.html", "classengine_1_1_model" ],
      [ "ModelRenderer", "structengine_1_1_model_renderer.html", "structengine_1_1_model_renderer" ],
      [ "ModelRenderSystem", "classengine_1_1_model_render_system.html", "classengine_1_1_model_render_system" ],
      [ "PhysicsSystem", "classengine_1_1_physics_system.html", "classengine_1_1_physics_system" ],
      [ "Pixel", "structengine_1_1_pixel.html", null ],
      [ "PolygonCollider", "structengine_1_1_polygon_collider.html", "structengine_1_1_polygon_collider" ],
      [ "Primitive", "classengine_1_1_primitive.html", "classengine_1_1_primitive" ],
      [ "PrimitiveRenderer", "structengine_1_1_primitive_renderer.html", "structengine_1_1_primitive_renderer" ],
      [ "PrimitiveRenderSystem", "classengine_1_1_primitive_render_system.html", "classengine_1_1_primitive_render_system" ],
      [ "Rigidbody", "structengine_1_1_rigidbody.html", "structengine_1_1_rigidbody" ],
      [ "Shader", "classengine_1_1_shader.html", "classengine_1_1_shader" ],
      [ "SpriteRenderer", "structengine_1_1_sprite_renderer.html", "structengine_1_1_sprite_renderer" ],
      [ "SpriteRenderSystem", "classengine_1_1_sprite_render_system.html", "classengine_1_1_sprite_render_system" ],
      [ "TextRenderer", "structengine_1_1_text_renderer.html", "structengine_1_1_text_renderer" ],
      [ "TextRenderSystem", "classengine_1_1_text_render_system.html", "classengine_1_1_text_render_system" ],
      [ "Texture", "classengine_1_1_texture.html", "classengine_1_1_texture" ],
      [ "TileProperty", "structengine_1_1_tile_property.html", null ],
      [ "Transform", "structengine_1_1_transform.html", "structengine_1_1_transform" ],
      [ "TransformSystem", "classengine_1_1_transform_system.html", "classengine_1_1_transform_system" ],
      [ "UIElement", "structengine_1_1_u_i_element.html", null ],
      [ "UISystem", "classengine_1_1_u_i_system.html", "classengine_1_1_u_i_system" ],
      [ "Vector2", "classengine_1_1_vector2.html", null ],
      [ "Vector3", "classengine_1_1_vector3.html", null ],
      [ "Vector4", "classengine_1_1_vector4.html", null ]
    ] ],
    [ "input", null, [
      [ "InputButton", "classinput_1_1_input_button.html", null ],
      [ "InputEvent", "classinput_1_1_input_event.html", "classinput_1_1_input_event" ],
      [ "InputValue", "structinput_1_1_input_value.html", null ]
    ] ],
    [ "Audio", "class_audio.html", "class_audio" ],
    [ "AudioEngine", "class_audio_engine.html", "class_audio_engine" ],
    [ "Character", "struct_character.html", "struct_character" ],
    [ "MapLayer", "class_map_layer.html", "class_map_layer" ],
    [ "SoundSystem", "struct_sound_system.html", null ],
    [ "Tilemap", "class_tilemap.html", "class_tilemap" ]
];