var classtesting_1_1gtest__printers__test_1_1_allows_generic_streaming_and_implicit_conversion_template =
[
    [ "operator bool", "classtesting_1_1gtest__printers__test_1_1_allows_generic_streaming_and_implicit_conversion_template.html#af5f8ea44d7d86283b4c004a994ddd7f9", null ]
];