var dir_e20ece8a4cb4e5a11c0dd0038d870d41 =
[
    [ "afblue.c", "afblue_8c.html", "afblue_8c" ],
    [ "afblue.h", "afblue_8h.html", "afblue_8h" ],
    [ "afcjk.c", "afcjk_8c.html", null ],
    [ "afcjk.h", "afcjk_8h.html", "afcjk_8h" ],
    [ "afcover.h", "afcover_8h.html", "afcover_8h" ],
    [ "afdummy.c", "afdummy_8c.html", null ],
    [ "afdummy.h", "afdummy_8h.html", null ],
    [ "aferrors.h", "aferrors_8h.html", "aferrors_8h" ],
    [ "afglobal.c", "afglobal_8c.html", "afglobal_8c" ],
    [ "afglobal.h", "afglobal_8h.html", "afglobal_8h" ],
    [ "afhints.c", "afhints_8c.html", "afhints_8c" ],
    [ "afhints.h", "afhints_8h.html", "afhints_8h" ],
    [ "afindic.c", "afindic_8c.html", null ],
    [ "afindic.h", "afindic_8h.html", null ],
    [ "aflatin.c", "aflatin_8c.html", "aflatin_8c" ],
    [ "aflatin.h", "aflatin_8h.html", "aflatin_8h" ],
    [ "afloader.c", "afloader_8c.html", "afloader_8c" ],
    [ "afloader.h", "afloader_8h.html", "afloader_8h" ],
    [ "afmodule.c", "afmodule_8c.html", "afmodule_8c" ],
    [ "afmodule.h", "afmodule_8h.html", "afmodule_8h" ],
    [ "afranges.c", "afranges_8c.html", "afranges_8c" ],
    [ "afranges.h", "afranges_8h.html", "afranges_8h" ],
    [ "afscript.h", "afscript_8h.html", "afscript_8h" ],
    [ "afshaper.c", "afshaper_8c.html", "afshaper_8c" ],
    [ "afshaper.h", "afshaper_8h.html", "afshaper_8h" ],
    [ "afstyles.h", "afstyles_8h.html", "afstyles_8h" ],
    [ "aftypes.h", "aftypes_8h.html", "aftypes_8h" ],
    [ "afws-decl.h", "afws-decl_8h.html", null ],
    [ "afws-iter.h", "afws-iter_8h.html", null ],
    [ "autofit.c", "autofit_8c.html", "autofit_8c" ],
    [ "ft-hb.c", "ft-hb_8c.html", "ft-hb_8c" ],
    [ "ft-hb.h", "ft-hb_8h.html", "ft-hb_8h" ]
];